version: "2.4"
services:
  go_genpdf:
    hostname: ${HOSTNAME}_go_genpdf
    container_name: ${COMPOSE_PROJECT_NAME}_go_genpdf
    image: ${REGISTRY_ADDRESS}/${COMPOSE_PROJECT_NAME}_go_genpdf:${GO_GENPDF_BRANCH}
    env_file:
      - .env
    ports:
      - "${INTERNAL_IP}:${GO_GENPDF_PORT}:8080"
    networks:
      - go_genpdf
    environment:
      - "PS1=$$(whoami)@$$(hostname):$$(pwd) $$ "
    logging:
      driver: "gelf"
      options:
        gelf-address: "udp://${GRAYLOG_HOST}:${GRAYLOG_PORT}"
        tag: "${HOSTNAME}"
    mem_limit: ${GO_GENPDF_MEMORY}

networks:
  go_genpdf: