version: "3"
services:
  go_genpdf:
    hostname: ${HOSTNAME}_go_genpdf
    container_name: unicom_go_genpdf
    build: .
    env_file:
      - .env
    ports:
      - "${GO_GENPDF_PORT}:8080"
    networks:
      - unicom_default
    environment:
      - "PS1=$$(whoami)@$$(hostname):$$(pwd) $$ "

networks:
  unicom_default:
    external: true